sudo: required
services:
  - docker
before_install:
  - docker build -t thiagoma1/docker-react -f Dockerfile.dev
script:
  - docker run -e CI=true thiagoma1/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region:
  app: "docker"
  name: "Docker-env"
  bucket_name: ""
  bucket_path: "docker"