version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /srv/app/node_modules
      - .:/srv/app
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /srv/app/node_modules
      - .:/srv/app
    command: ["npm", "run", "test"]